plex:
  build: plex/
  ports:
    - "32400:32400"
  volumes:
    - plex/config:/var/lib/plexmediaserver
    - /media/jdb/Big Drive/media:/plex
  restart: always
  stdin_open: true
  tty: true
utserver:
  build: utorrent/
  ports:
    - "6881:6881"
    - "8080:8080"
  volumes:
    - /media/jdb/Big Drive/Downloads:/utserver
  restart: always
  stdin_open: true
  tty: true
