plex:
  build: plex/
  ports:
    - "32400:32400"
  volumes:
    - config/:/var/lib/plexmediaserver
    - ~/Google Drive/music:/plex/media
  restart: always
  stdin_open: true
  tty: true
utserver:
  build: utorrent/
  ports:
    - "6881:6881"
    - "8080"
  volumes:
    - ./ut_data:/data
  restart: always
  stdin_open: true
  tty: true
